### ISSUE TITLE
App has crashed after tapped item on sponsor page, if all of browser apps had been disabled

### ISSUE THREAD

**Issue by k3nsuk3** [DroidKaigi/conference-app-2020#402]
**Overview (Required)**
- App has crashed with following exception after tapped item on sponsor page, if all of browser apps had been disabled:

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: io.github.droidkaigi.confsched2020.debug, PID: 336
    android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=https://corp.zozo.com/... (has extras) }
        at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2058)
        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1716)
        at android.app.Activity.startActivityForResult(Activity.java:5211)
        at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:675)
        at android.app.Activity.startActivityForResult(Activity.java:5169)
        at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:662)
        at android.app.Activity.startActivity(Activity.java:5540)
        at androidx.core.content.ContextCompat.startActivity(ContextCompat.java:251)
        at androidx.browser.customtabs.CustomTabsIntent.launchUrl(CustomTabsIntent.java:263)
        at io.github.droidkaigi.confsched2020.ui.ChromeCustomTabsNavigator.navigate(ChromeCustomTabsNavigator.kt:41)
        at io.github.droidkaigi.confsched2020.ui.ChromeCustomTabsNavigator.navigate(ChromeCustomTabsNavigator.kt:18)
        at androidx.navigation.NavController.navigate(NavController.java:933)
        at androidx.navigation.NavController.navigate(NavController.java:867)
        at androidx.navigation.NavController.navigate(NavController.java:804)
        at androidx.navigation.NavController.navigate(NavController.java:790)
        at androidx.navigation.NavController.navigate(NavController.java:985)
        at io.github.droidkaigi.confsched2020.sponsor.ui.item.LargeSponsorItem$bind$1.onClick(LargeSponsorItem.kt:26)
        at android.view.View.performClick(View.java:7259)
        at android.view.View.performClickInternal(View.java:7236)
        at android.view.View.access$3600(View.java:801)
        at android.view.View$PerformClick.run(View.java:27892)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

**Steps To Reproduce**

1. Disable all of browser apps via System Settings
2. Open sponsor page on this app
3. Tap any one of the sponsor items

**Expected behavior**
Notify user to enable browser app to open it.

**Env:**
 - Device: Pixel 3a emulator, Essential Phone
 - OS: 9.0, 10.0
 - App Version or the branch: master [0f8d476e0efcc13b2720940e961fb2bd80694b59]

---

I'm not sure whether to need to fix this. Could you close this issue if it won't fix because this situation is rare case.

**Comment by takahirom** [comment]
Thanks! I think we should try-catch!

**Comment by iaia** [comment]
I'll try this issue.
