### ISSUE TITLE
Class not found error when R8 Enabled

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2020#691]
## Kind (Required)

- Improvement

 ## Overview (Required)

- 

Add `minifyEnabled true`

```
buildTypes {
        debug {
            minifyEnabled true
```

And `./gradlew android-base:installDebug`

```
02-02 00:56:42.645 10963-10963/io.github.droidkaigi.confsched2020.debug E/AndroidRuntime: FATAL EXCEPTION: main
    Process: io.github.droidkaigi.confsched2020.debug, PID: 10963
    java.lang.RuntimeException: Unable to start activity ComponentInfo{io.github.droidkaigi.confsched2020.debug/io.github.droidkaigi.confsched2020.MainActivity}: android.view.InflateException: Binary XML file line #52: Error inflating class fragment
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2298)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2360)
        at android.app.ActivityThread.access$800(ActivityThread.java:144)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5221)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
     Caused by: android.view.InflateException: Binary XML file line #52: Error inflating class fragment
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:763)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
        at androidx.appcompat.app.g.c(:555)
        at androidx.appcompat.app.d.setContentView(:161)
        at androidx.databinding.f.a(:303)
        at androidx.databinding.f.a(:284)
        at io.github.droidkaigi.confsched2020.MainActivity$c.invoke(:75)
        at io.github.droidkaigi.confsched2020.MainActivity$c.invoke(:73)
        at l.r.getValue(:74)
        at io.github.droidkaigi.confsched2020.MainActivity.q()
        at io.github.droidkaigi.confsched2020.MainActivity.onCreate(:102)
        at android.app.Activity.performCreate(Activity.java:5937)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2251)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2360) 
        at android.app.ActivityThread.access$800(ActivityThread.java:144) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:135) 
        at android.app.ActivityThread.main(ActivityThread.java:5221) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694) 
     Caused by: java.lang.RuntimeException: Exception inflating io.github.droidkaigi.confsched2020.debug:navigation/navigation line 70
        at androidx.navigation.s.a(:90)
        at androidx.navigation.NavController.b(:499)
        at androidx.navigation.NavController.b(:481)
        at androidx.navigation.fragment.d.c(:237)
        at androidx.fragment.app.Fragment.h(:2684)
        at androidx.fragment.app.r.c(:270)
        at androidx.fragment.app.m.a(:1173)
        at androidx.fragment.app.m.j(:1354)
        at androidx.fragment.app.k.onCreateView(:109)
        at androidx.fragment.app.h.a(:135)
        at androidx.fragment.app.d.a(:356)
        at androidx.fragment.app.d.onCreateView(:335)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:733)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:806) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:809) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:504) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:414) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:365) 
        at androidx.appcompat.app.g.c(:555) 
        at androidx.appcompat.app.d.setContentView(:161) 
        at androidx.databinding.f.a(:303) 
        at androidx.databinding.f.a(:284) 
        at io.github.droidkaigi.confsched2020.MainActivity$c.invoke(:75) 
        at io.github.droidkaigi.confsched2020.MainActivity$c.invoke(:73) 
        at l.r.getValue(:74) 
        at io.github.droidkaigi.confsched2020.MainActivity.q() 
        at io.github.droidkaigi.confsched2020.MainActivity.onCreate(:102) 
        at android.app.Activity.performCreate(Activity.java:5937) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2251) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2360) 
        at android.app.ActivityThread.access$800(ActivityThread.java:144) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:135) 
        at android.app.ActivityThread.main(ActivityThread.java:5221) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694) 
     Caused by: java.lang.RuntimeException: java.lang.ClassNotFoundException: io.github.droidkaigi.confsched2020.model.SessionPage
        at androidx.navigation.u.a(:181)
        at androidx.navigation.s.a(:182)
        at androidx.navigation.s.a(:146)
        at androidx.navigation.s.a(:121)
        at androidx.navigation.s.a(:132)
        at androidx.navigation.s.a(:81)
        at androidx.navigation.NavController.b(:499) 
        at androidx.navigation.NavController.b(:481) 
        at androidx.navigation.fragment.d.c(:237) 
        at androidx.fragment.app.Fragment.h(:2684) 
        at androidx.fragment.app.r.c(:270) 
        at androidx.fragment.app.m.a(:1173) 
        at androidx.fragment.app.m.j(:1354) 
        at androidx.fragment.app.k.onCreateView(:109) 
        at androidx.fragment.app.h.a(:135) 
        at androidx.fragment.app.d.a(:356) 
        at androidx.fragment.app.d.onCreateView(:335) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:733) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:806) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:809) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:504) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:414) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:365) 
        at androidx.appcompat.app.g.c(:555) 
        at androidx.appcompat.app.d.setContentView(:161) 
        at androidx.databinding.f.a(:303) 
        at androidx.databinding.f.a(:284) 
        at io.github.droidkaigi.confsched2020.MainActivity$c.invoke(:75) 
        at io.github.droidkaigi.confsched2020.MainActivity$c.invoke(:73) 
        at l.r.getValue(:74) 
        at io.github.droidkaigi.confsched2020.MainActivity.q() 
        at io.github.droidkaigi.confsched2020.MainActivity.onCreate(:102) 
        at android.app.Activity.performCreate(Activity.java:5937) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2251) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2360) 
        at android.app.ActivityThread.access$800(ActivityThread.java:144) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:135) 
        at android.app.ActivityThread.main(ActivityThread.java:5221) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694) 
     Caused by: java.lang.ClassNotFoundException: io.github.droidkaigi.confsched2020.model.SessionPage
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:308)
        at java.lang.Class.forName(Class.java:272)
        at androidx.navigation.u.a(:169)
        at androidx.navigation.s.a(:182) 
        at androidx.navigation.s.a(:146) 
        at androidx.navigation.s.a(:121) 
        at androidx.navigation.s.a(:132) 
        at androidx.navigation.s.a(:81) 
        at androidx.navigation.NavController.b(:499) 
        at androidx.navigation.NavController.b(:481) 
        at androidx.navigation.fragment.d.c(:237) 
        at androidx.fragment.app.Fragment.h(:2684) 
        at androidx.fragment.app.r.c(:270) 
        at androidx.fragment.app.m.a(:1173) 
        at androidx.fragment.app.m.j(:1354) 
        at androidx.fragment.app.k.onCreateView(:109) 
        at androidx.fragment.app.h.a(:135) 
        at androidx.fragment.app.d.a(:356) 
        at androidx.fragment.app.d.onCreateView(:335) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:733) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:806) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:809) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:504) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:414) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:365) 
        at androidx.appcompat.app.g.c(:555) 
        at androidx.appcompat.app.d.setContentView(:161) 
        at androidx.databinding.f.a(:303) 
        at androidx.databinding.f.a(:284) 
        at io.github.droidkaigi.confsched2020.MainActivity$c.invoke(:75) 
        at io.github.droidkaigi.confsched2020.MainActivity$c.invoke(:73) 
        at l.r.getValue(:74) 
        at io.github.droidkaigi.confsched2020.MainActivity.q() 
        at io.github.droidkaigi.confsched2020.MainActivity.onCreate(:102) 
        at android.app.Activity.performCreate(Activity.java:5937) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2251) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2360) 
        at android.app.ActivityThread.access$800(ActivityThread.java:144) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:135) 
        at android.app.ActivityThread.main(ActivityThread.java:5221) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694) 
     Caused by: java.lang.ClassNotFoundException: Didn't find class "io.github.droidkaigi.confsched2020.model.SessionPage" on path: DexPathList[[zip file "/data/app/io.github.droidkaigi.confsched2020.debug-2/base.apk", zip file "/data/app/io.github.droidkaigi.confsched2020.debug-2/split_config.en.apk", zip file "/data/app/io.github.droidkaigi.confsched2020.debug-2/split_config.xxhdpi.apk", zip file "/data/app/io.github.droidkaigi.confsched2020.debug-2/split_contributor.apk", zip file "/data/app/io.github.droidkaigi.confs
```

 ## Links	

-

**Comment by takahirom** [comment]
Sorry. This was simply not able to reference proguardFile.
